### ISSUE TITLE
Stubbing modules in test

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#152]
The last missing piece to make this boilerplate have all of the features of my non-ES6 boilerplate is the ability to stub modules in tests.

If I pull in A, and A requires B, I should be able to stub out B to be whatever I want. [Proxyquire](https://github.com/thlorenz/proxyquire) competes with Babel (they both override `require`), so I was unable to figure out integrating those two.

**Comment by Kflash** [comment]
@jmeas any online references to this so I understand better your needs?

**Comment by jmeas** [comment]
Related: https://github.com/thlorenz/proxyquire/issues/64

**Comment by jmeas** [comment]
I just tested to see if proxyquire worked, and it still does not. I updated `another-test.js` to begin with:

```js
var proxyquire = require('proxyquire');

var Another = proxyquire('../../src/another', {
  anotherFn: function() {
    return 'pls';
  },
  sandwich: true
});
```

No dice!

If anyone is writing ES6 tests **and** found a way to stub modules, I'm super curious to know your tricks!

**Comment by vvo** [comment]
@jmeas Same for me, I cannot use proxyquire when using `babel-node` :(

**Comment by jmeas** [comment]
I'm unsure if it's proxyquire + babel that are incompatible, or proxyquire + browserify (or...both?). I plan to make some isolated test cases of both to see if I can make any progress on this feature.

**Comment by jmeas** [comment]
Webpack's method of supporting this is here: https://github.com/plasticine/inject-loader

**Comment by jmeas** [comment]
Once webpack lands in #259 this will just be a matter of adding a page to the Wiki.

**Comment by jmeas** [comment]
Webpack does support this for the browser tests, but obv. I'm not using webpack for the server tests. To use the same syntax for both, I'll need to build the app to run the Node tests, too, I suppose...

**Comment by jmeas** [comment]
Example using the above module for the browser:

```js
var MyModuleInjector = require('inject!../../src/generator-tests');

var betterName = {
  name: 'sam'
};

var generatorTests = MyModuleInjector({
  './file-two': betterName
});
```

**Comment by jmeas** [comment]
If I get rid of the Node tests for the browser, and instead use PhantomJS, then this is a non-issue.

I guess I should do Karma for the browser and Node for the server, exclusively?

**Comment by jmeas** [comment]
Reopening because there are libraries that might work in both Node and the browser that you want to test in both scenarios. I think the only way to support that is through Browserify. So I might need to go back on all of the webpack changes for the browser tests, hah : P

**Comment by jmeas** [comment]
Gonna figure this out in #277
