### ISSUE TITLE
preversion and prepublish

### ISSUE THREAD

**Issue by thejameskyle** [babel/generator-babel-boilerplate#179]
https://github.com/thejameskyle/a-damn-nice-test-repo/blob/master/package.json#L8-L9

```json
"scripts": {
  "preversion": "[[ -z $(git status --porcelain) ]] && npm run build && git add -A dist && git commit -m 'Build lib'",
  "prepublish": "git push origin master --follow-tags"
}
```

`npm version` will check for a clean repo, run the build, add the `dist` directory, commit the changes, and then run the rest of `npm version`.

`npm prepublish` will push the master branch and any tags to master before publishing on npm.

**Comment by jmeas** [comment]
This is some fancy stuff. I'm leaning in favor of this, but I'll have to think more on it. It seems like there's some overlap between this and #81 ?

**Comment by thejameskyle** [comment]
Yup, I would personally prefer this over Make

**Comment by jmeas** [comment]
The preversion stuff is < 1 month old, so I think we should take @megawac 's hint (https://github.com/babel/babel-library-boilerplate/pull/192#issuecomment-126404164) and not add it just yet. Maybe in another month or two?

In the meantime, we can add in `postpublish`?

How's that sound?

**Comment by jmeas** [comment]
Closed the PR cause `preversion` is more useful than `postpublish`. I'll revisit in a few weeks/month(s).

**Comment by jmeas** [comment]
Gonna close, but mark as revisit.
