### ISSUE TITLE
Remove config data from package.json

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#185]
I originally put the boilerplate config in the package.json per @thejameskyle's suggestion. @megawac thinks it'd be better to put it in the gulpfile.

I'm fine either way, honestly. Any strong opinions here?

**Comment by thejameskyle** [comment]
No strong opinions

**Comment by jmeas** [comment]
@megawac what you think?

**Comment by megawac** [comment]
I'd like to see it moved elsewhere - probably just gulpfile IMO

**Comment by thejameskyle** [comment]
Yeah the gulpfile is good

**Comment by jmeas** [comment]
k will change

**Comment by jmeas** [comment]
Prob depends on https://github.com/mochajs/mocha/issues/1457#issuecomment-127060321

**Comment by jmeas** [comment]
@thejameskyle / @megawac I think I've got three choices:

1. leave it the way that it is
2. duplicate the mocha globals in two places (Gulpfile and browserify setup file)
3. create an external file just for the mocha configuration

Thoughts?

**Comment by paulfalgout** [comment]
4. I think you should have an external json file for the mocha globals and the eslintrc file in the test directory should extend from it so you're not setting them there as well.

**Comment by jmeas** [comment]
I'm going to close this because of @paulfalgout 's awesome change made here https://github.com/babel/generator-babel-boilerplate/commit/ceb2941bbd74b3acb34a12732b974d361d57463e

If anyone else has any ideas for further ways to optimize the configuration, do let me know!
