### ISSUE TITLE
Investigate UMD with no global export with webpack

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#198]
At some point my hack for getting around Esperanto's inability to export global variables no longer works. I should:

1. Update the README to remove the workaround

And 

1. Look into alternative module loaders that can bundle UMD w.o. exporting a global
2. or finish this PR lol https://github.com/esperantojs/esperanto/pull/109

Ref https://github.com/esperantojs/esperanto/issues/96

**Comment by paulfalgout** [comment]
:exclamation: oh no  :crying_cat_face:

**Comment by jmeas** [comment]
I kno : [

**Comment by paulfalgout** [comment]
Well I guess there's no need to finish the PR? https://github.com/babel/generator-babel-boilerplate/issues/219

**Comment by jmeas** [comment]
@paulfalgout, you're right – there's no reason to finish that Esperanto PR. But this issue is still a valid one. Hopefully #219 fixes it!

**Comment by jmeas** [comment]
Once #259 lands I should investigate whether webpack makes this any easier

**Comment by jmeas** [comment]
Gonna close in favor of #264
