### ISSUE TITLE
Simplify copying of files

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#199]
https://github.com/babel/generator-babel-boilerplate/pull/197#discussion_r36120294

This greatly simplifies the file copying logic, but it breaks from the Yeoman naming conventions. Is that worth it? Probably, but I'm going to think about it for awhile.

**Comment by jmeas** [comment]
If I had to guess, the Yeoman naming conventions are there because `package.json` is a special file, but `_package.json` is not. I'm not sure how important it is to separate that out, though...it's not like anyone is going to go into their global npm install directory and run an `npm` command in this directory.

@thejameskyle / @megawac what do you think?

**Comment by megawac** [comment]
Yeah, I think its a non issue to consider

**Comment by jmeas** [comment]
Yeah I'll prob. update to use the simpler code

**Comment by jmeas** [comment]
Done
