### ISSUE TITLE
Optional CodeClimate

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#201]
Should I add the ability for users to turn this off when making their project?

**Comment by jmeas** [comment]
yes I should

**Comment by jmeas** [comment]
One thing I want to avoid is too many questions when creating this thing. It should install with as few questions as possible with reasonable defaults. I'm thinking CodeClimate will be turned off by default, then a sub-generator can be used to install it later.

**Comment by megawac** [comment]
Maybe just hide it behind a flag, off by default?

**Comment by jmeas** [comment]
:+1:

**Comment by jmeas** [comment]
Closing in favor of #263
