### ISSUE TITLE
Add source maps for browser tests

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#209]

**Comment by marcandre** [comment]
:+1:, was going to open an issue for this.

I feel this is a biggie, makes debugging quite hard without it. Navigating a 12k line JS file isn't super fun...

**Comment by jmeas** [comment]
PRs welcome.

**Comment by jasonLaster** [comment]
Yup, this is what i'm seeing as well.

are there any good docs on how to go about doing this?

![source-maps](https://cloud.githubusercontent.com/assets/254562/10253659/876a69ac-690c-11e5-85a3-af6cd9b0720b.jpg)

**Comment by jmeas** [comment]
Hey there, @jasonLaster!

Browserify is used for the browser tests, so it's likely to involve flicking on the correct Browserify option.

[Browserify's options](https://github.com/substack/node-browserify#usage) are in the repo README. The option to enable source maps is `debug`. A quick glance at this boilerplate suggests to me that it might need to be added [here](https://github.com/babel/generator-babel-boilerplate/blob/62cbe1884bc1d6661303ff756281a50bd050643a/app/templates/gulpfile.babel.js#L117).

Maybe something like `_.extend(watchify.args, {debug: true});` would do the trick?

**Comment by jmeas** [comment]
Done! Will be released as part of v6 sometime soon

**Comment by marcandre** [comment]
:clap: :fireworks:
