### ISSUE TITLE
Weird default username output

### ISSUE THREAD

**Issue by thejameskyle** [babel/generator-babel-boilerplate#216]
coming through as `thejameskyle\n,`

![screen shot 2015-08-10 at 1 11 03 pm](https://cloud.githubusercontent.com/assets/952783/9183022/a9474696-3f61-11e5-8a26-bffc14520901.png)

**Comment by jmeas** [comment]
ping @megawac. any cluez?

**Comment by megawac** [comment]
`trim` all the things?

**Comment by thejameskyle** [comment]
It could be that it is an array: 

```js
_.trim(['thejameskyle\n', '']) >> "thejameskyle\n,"
```

**Comment by jmeas** [comment]
Weird - the same thing is happening to me. This is a new bug!

**Comment by jmeas** [comment]
Not happening to me anymore. @thejameskyle, are you still experiencing this? In other werdz, what does `npm whoami` return for you?

**Comment by jmeas** [comment]
Notes for future James: [`npm adduser`](https://docs.npmjs.com/cli/adduser) sets the `username` config property that `npm whoami` returns. This couldn't possible be an Array, right? So I'm not too sure why this would happen.

**Comment by jmeas** [comment]
ping @thejameskyle. Still having this issue?

**Comment by jmeas** [comment]
Just got this issue...it may be a problem with npm3? Will investigate further soon...

**Comment by thejameskyle** [comment]
I haven't looked at it in awhile

**Comment by jmeas** [comment]
This is the most bizarre thing. On npm 2.14.7 and npm 3.3.12, the boilerplate's code returns:

`[ [ 'jmeas\n', '' ] ]`

That is, a nested array with the first value being `jmeas\n`.

Running that same exact code outside of the boilerplate results in `[ 'jmeas\n' ]`.

Pretty crazy stuff.

**Comment by jmeas** [comment]
Upgrading to Bluebird v3 fixes this. Pushing a bug fix now.
