### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by thejameskyle** [babel/generator-babel-boilerplate#217]
So this generator currently is targeting libraries that are meant for either the browser or node, however since yeoman is now in place it would be nice to handle a bit more.

It'd be cool to be able to generate a tool with a CLI. See [generator-nm](https://github.com/sindresorhus/generator-nm) for inspiration.

**Comment by jmeas** [comment]
"with a CLI." What might the CLI do?

**Comment by thejameskyle** [comment]
?

If you're writing a tool with a CLI, you want the boilerplate for the CLI to be there.

**Comment by jmeas** [comment]
Ah, gotcha. :+1:

**Comment by jmeas** [comment]
This will land in the version after the next version (the next being v6).

**Comment by jmeas** [comment]
Gonna merge this into #263
