### ISSUE TITLE
Move away from Esperanto, as it is deprecated

### ISSUE THREAD

**Issue by paulfalgout** [babel/generator-babel-boilerplate#219]
[DEPRECATION NOTICE](https://github.com/esperantojs/esperanto#this-project-is-no-longer-under-active-development-to-bundle-es6-modules-use-rollup-to-convert-es6-modules-to-another-format-use-babel-see-191-for-details) Esperanto is no longer under active development.

Now what?

**Comment by jmeas** [comment]
Rollup

**Comment by jmeas** [comment]
hmmm..maybe actually need to use Babel instead. Not sure if Rollup does any conversion.

**Comment by jmeas** [comment]
Rollup's API is, perhaps unsurprisingly, [very similar to Esperanto's](https://github.com/rollup/rollup/wiki/JavaScript-API). And until Babel [can inline all dependencies](https://github.com/babel/babel/issues/1681) I think I'll need to continue relying on third party deps.

shucks!

**Comment by kristianmandrup** [comment]
Yeah, WTF!? :O

```sh
22:52 $ npm test

> seneca-async@0.0.1 test /Users/kristianmandrup/repos/test123/senaca-projects/seneca-async
> gulp

[DEPRECATION NOTICE] Esperanto is no longer under active development. To convert an ES6 module to another format, consider using Babel (https://babeljs.io)
[22:53:48] Using gulpfile ~/repos/test123/senaca-projects/seneca-async/gulpfile.js
[22:53:48] Starting 'test'...



  0 passing (0ms)

[22:53:48] Finished 'test' after 744 ms
```

I have all my tests in `test/*.test.js` with this gulpfile config as provided by https://github.com/babel/generator-babel-boilerplate, modified a tiny bit:

```js
var testFiles = glob.sync('./test/**/*.test.js');

...

function getBundler() {
  // Our browserify bundle is made up of our unit tests, which
  // should individually load up pieces of our application.
  // We also include the browserify setup file.
  var testFiles = glob.sync('./test/**/*.test.js');
```

Why are no tests run? I have the `test/setup/node.js` file. What else could be missing? I suspect it is not due to the deprecation warning?

**Comment by jmeas** [comment]
Hi @kristianmandrup , can you make a separate issue? Thanks!

**Comment by kristianmandrup** [comment]
Sorry, was just tired and frustrated last night :P Will do!

**Comment by Harris-Miller** [comment]
A heads up: Rollup uses Acornjs for it's js AST. and as far as I can tell, Acornjs does not support ES7 decorators yet. Just trying to use Rollup on it's own throws an error for an unexpected character '@',

**Comment by jmeas** [comment]
Closing in favor of #230
