### ISSUE TITLE
How to launch test-browser?

### ISSUE THREAD

**Issue by ivitivan** [babel/generator-babel-boilerplate#220]
Hi!

I can not launch tests in browser. `gulp test-browser` runs without errors, but no page shows up in the browser. I manually checked `localhost:35729` and it works but I get only hello message.

**Comment by jmeas** [comment]
Open [this file](https://github.com/babel/generator-babel-boilerplate/blob/master/app/templates/test/runner.html) in your browser after you have run the command.

**Comment by ivitivan** [comment]
It works! Thank you!
