### ISSUE TITLE
The code generator has deoptimised the styling of [some file] as it exceeds the max of ”100KB“

### ISSUE THREAD

**Issue by Kflash** [babel/generator-babel-boilerplate#221]
Any workaround for this?? It's kinda urgent.

`The code generator has deoptimised the styling of [some file] as it exceeds the max of ”100KB“`

**Comment by jmeas** [comment]
I've never seen this before. Which part of the boilerplate is emitting this?

Also, is it a warning or is it an error? As in, does it still build?

**Comment by jmeas** [comment]
[Ref](http://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e). All I did was google the error :stuck_out_tongue:

**Comment by Kflash** [comment]
Hi. Me too googlet the error and put it to compact mode, but it still occur sometimes. And I also now get messages that Esperanto hate ES6 promises and are deprecated

**Comment by jmeas** [comment]
Hm, interesting. I've never had an issue with Esperanto and Promises. I'm working on switching out Babel for Esperanto over here: #219.

**Comment by Kflash** [comment]
All issues I got happend right after I exceeded 100KB. But you can also trigger a Esperanto error and Babel will not see the issue. Try ` import XXX form ` I misspelled `from`. 
I hope you get rid of the Esperanto soon, it have been 30 minutes fight now before I found workarounds.

**Comment by jmeas** [comment]
Sorry that it's causing you frustration! I should have time to move off of Esperanto in a few days.

**Comment by Kflash** [comment]
It's all ok. I found a workaround that works, and until you fix this I can accept too see the red warning text :)

**Comment by jmeas** [comment]
> It's all ok. I found a workaround that works

Awesome! Glad to hear it!

> until you fix this I can accept too see the red warning text :)

Thanks for your patience :)

Is this issue good to be closed, then?

**Comment by Kflash** [comment]
@jmeas Yup, you can close this.

**Comment by jmeas** [comment]
Will do, then. @kflash, I'll ping you when Esperanto has been removed from the Boilerplate!
