### ISSUE TITLE
Async/await mocha testing?

### ISSUE THREAD

**Issue by kristianmandrup** [babel/generator-babel-boilerplate#226]
I'm trying to test a project using the new ES7 async/await constructs. 
Does this project support "babel" async or would I have to combine with a different setup, something like: https://github.com/bmancini55/babel-mocha-test

There is also: https://www.npmjs.com/package/mochawait, mocha-babel and a host of others (such as chai-as-promised) etc. Thanks.

**Comment by jmeas** [comment]
Thanks for the issue! I need to investigate this further, though it might be an issue with a dependency of Esperanto. #218 covers this topic, so I'm going to go ahead and close this as a duplicate.

**Comment by kristianmandrup** [comment]
Thanks :) Please fix the Esperanto issue ASAP. I got my project working with async for now, but I'm sure your generator template could be further improved to be ready for ES7 async scenarios. Cheers!
Also the gulpfile error handling could be better. This one really helped me out :)

```js
var gulp_src = gulp.src;
gulp.src = function() {
  return gulp_src.apply(gulp, arguments)
    .pipe($.plumber(function(error) {
      console.log(error.stack);
      // Output an error message
      gutil.log(gutil.colors.red('Error (' + error.plugin + '): ' + error.message));
      // emit the end event, to properly end the task
      this.emit('end');
    })
  );
};
```

**Comment by jmeas** [comment]
> Please fix the Esperanto issue ASAP.

I'm not sure when I'll be able to look into it. PRs are always welcome if you figure it out!
