### ISSUE TITLE
can't build distro build

### ISSUE THREAD

**Issue by Kflash** [babel/generator-babel-boilerplate#227]
Hi. I discovered it yesterday and thought it was a mistake I did when I put up a new workflow, but I experienced it just now with my old workflow as well. 

Problem is that I can't build a distro build. `gulp build` doesn't work. Everything looks just fine, but no folder created and no file compiled.

I don't know how to solve it, or re-produce it. However it seems to be Esperanto fucking things up AGAIN!

**Comment by jmeas** [comment]
@kflash, is there an example repo up somewhere? This boilerplate has been working fine for me (I prob make 1-2 new projects with it a week).

**Comment by Kflash** [comment]
As stated it isn't.

Anyhow. You wrote earlier Esperanto should be removed within 4 days. Now it
has gone 12 days and no progress.

When will this be solved?

**Comment by jmeas** [comment]
I work on this in my free time. If you want to make a PR, by all means go for it. : P Otherwise, it'll happen sometime soon-ish.

**Comment by Kflash** [comment]
I will just wait. After all this is a very good boilerplate now :)

**Comment by jmeas** [comment]
> After all this is a very good boilerplate now :)

Thanks, man! It's feedback from folks like you that keep making it get better and better!

**Comment by jmeas** [comment]
Without any details, there's nothing I can do to help. If you've identified Esperanto as the problem, then this will be resolved by #219. Gonna close for now, but lmk if you can make a reproducible test case and I'll happily look into it further!
