### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by marcandre** [babel/generator-babel-boilerplate#232]
Unless I'm missing something, there's no builtin way to specify a banner for the resulting `dist/xyzz.js` file.

I think this would be helpful to just about anybody using this project.

Thanks

**Comment by jmeas** [comment]
Hey there, @marcandre ! You're not missing anything. The banner was intentionally left out, as I think it's one of those things that:

1. not everyone needs
2. is pretty simple to add back in

Now that this is a Yeoman generator, I might consider toggling it on/off with a flag. How's that sound to you?

**Comment by marcandre** [comment]
Anything you want to do to help is welcome.

TBH, I'm a complete n00b with respect to JS tool chain, have little interest in spending time learning much of it, so projects like this one are a real boon for slakers like me...

**Comment by jmeas** [comment]
> I'm a complete n00b with respect to JS tool chain

We're all learning :) This project was my first (and only) Gulpfile... :stuck_out_tongue:

**Comment by jmeas** [comment]
@marcandre do you want the banner in the minified version as well? Or just the non-minified build?

**Comment by jmeas** [comment]
Gonna merge this issue with #263 , as it'll be a part of that CLI. Feel free to leave a reply here or there @marcandre ~

**Comment by marcandre** [comment]
With `parsley`, we have the header in minified version too.

**Comment by jmeas** [comment]
Awesome, thanks! I'll make sure it shows up in both versions, then.
