### ISSUE TITLE
Beep instead of notify?

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#246]
What OS' does notify work on? Should it beep on error instead?

Update: it works on Windows, Linux, and OSX, so that's good. Should it still beep instead tho'? Or do both?

//cc @megawac / @thejameskyle

**Comment by jmeas** [comment]
Gonna keep it as a notification for now. Feel free to comment here if you'd prefer a beep

**Comment by thejameskyle** [comment]
I actually would really prefer a beep. The notification is overly distracting

**Comment by jmeas** [comment]
I'll change it to a beep in v6 then! If I miss my notification too much, then I'll add a flag option. :)

**Comment by jmeas** [comment]
Done
