### ISSUE TITLE
Suggestions for future versions

### ISSUE THREAD

**Issue by Kflash** [babel/generator-babel-boilerplate#272]
Why not try to support either out of the box what people use daily, og set as option flag for Yeoman?

- code climate I see you will set as a option. It's ok. But consider support for coveralls? Many people use that as well.

- options for server variables? 

- option between mocha and jasmine?

**Comment by jmeas** [comment]
Thanks for the suggestions!

> But consider support for coveralls? Many people use that as well.

I'll consider that.

> options for server variables?

What do you mean? There's (intentionally) no server in the boilerplate, and I don't think that there should be.

> option between mocha and jasmine?

Hmm...gonna say no on this one for now.

**Comment by jmeas** [comment]
Also, fwiw these features, should they land, would be post-v6. I've got v6 all scoped out!

**Comment by Kflash** [comment]
Just some suggestions. It's all up to you. But Angular etc uses karma / jasmine, and very popular etc. In case someone would use this boilerplate for Angular.

**Comment by jmeas** [comment]
Angular's documentation suggests you use Jasmine, but you can just as easily use Mocha. I use Mocha with Angular all the time; my current project at work is an Angular + Mocha app.

**Comment by Kflash** [comment]
Again just suggestions. And also JSX support you maybe can add to the list

**Comment by jmeas** [comment]
I've been thinking about what the future of this boilerplate might look like. Advanced configuration like this is a part of some of the options that I'm considering. I'm going to close this for now, but I'm going to come revisit this when the time comes to focus more on those questions.

Thanks for the awesome suggestions, @kflash!
