### ISSUE TITLE
Use screw_ie8 flag

### ISSUE THREAD

**Issue by Kflash** [babel/generator-babel-boilerplate#273]
To minimize the file better, why not use the UglifyJsPlugin and the screw_i8 flag? Like this:

```
new webpack.optimize.UglifyJsPlugin({
			minimize: true,
			compressor: {
				screw_ie8: true,
				warnings: false
			}
		})
	);
```

**Comment by jmeas** [comment]
I'm already minifying with UglifyJS [using Gulp](https://github.com/babel/generator-babel-boilerplate/blob/502799992a9a453ddd6c9645429bc4ba351f5e40/app/templates/gulpfile.babel.js#L83). If you don't need IE8 support, then you can go ahead and switch this on after making a new project.

I aim for IE8 support in most of my libs to maximize the # of people that can use them :)

Gonna close!
