### ISSUE TITLE
uknown error when I compile

### ISSUE THREAD

**Issue by Kflash** [babel/generator-babel-boilerplate#282]
<--- Last few GCs --->

   10972 ms: Scavenge 1397.6 (1455.2) -> 1397.6 (1455.2) MB, 3.3 / 0 ms (+ 8.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   12201 ms: Mark-sweep 1397.6 (1455.2) -> 1397.6 (1455.2) MB, 1228.6 / 0 ms (+ 88.0 ms in 407 steps since start of marking, biggest step 12.0 ms) [last resort gc].
   13375 ms: Mark-sweep 1397.6 (1455.2) -> 1397.6 (1455.2) MB, 1174.6 / 0 ms [last resort gc].

**Comment by jmeas** [comment]
Paste the whole thing in a gist? Also, what version of Node/npm/this generator?

**Comment by Kflash** [comment]
Sorry for late replies. Just close this one. I solved my own issues.
https://github.com/Kflash/trolly

**Comment by jmeas** [comment]
No problem!
