### ISSUE TITLE
Babel v6

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#284]
Time to upgrade! This boilerplate should prob. use the ES2015 preset.

**Comment by paulfalgout** [comment]
FYI: https://github.com/douglasduteil/isparta/issues/81

**Comment by jmeas** [comment]
I'll keep an eye on that issue. Thanks!

**Comment by iamstarkov** [comment]
i made a [babel-init](https://github.com/iamstarkov/generator-babel-init) generator to easily start new projects with babel support. And it works great with other generators as well. So if `babel-boilerplate` will be just composed with `babel-init` then this issue will be resolved for free. and its easy:

```js
this.composeWith('babel-init', {}, {
  local: require.resolve('generator-babel-init/generators/app')
});
```

I can create pull-request to make it happen, if you will find this helpfull

**Comment by paulfalgout** [comment]
Isparta is ready to go.  I can move this to v6 in the next couple days I think.

**Comment by thejameskyle** [comment]
ping

**Comment by jmeas** [comment]
Nice @paulfalgout. Let me know before you start; I might have time these next few days, too.

**Comment by jmeas** [comment]
@iamstarkov I'm going to take a look at your generator for future iterations of this project. Sounds neat!
