### ISSUE TITLE
isparta no longer compatible

### ISSUE THREAD

**Issue by marcandre** [babel/generator-babel-boilerplate#286]
Looks like current `isparta` (3.5.x) is no longer compatible with the `coverage` gulp task.
Travis was thus [failing](https://travis-ci.org/guillaumepotier/Parsley.js/builds/88948241)
I [forced v3.0.x](https://github.com/guillaumepotier/Parsley.js/commit/b52efb733eddf13f0c148dd829dd038dda151e0e)
It's now [passing](https://travis-ci.org/guillaumepotier/Parsley.js/builds/88948889)

I did not investigate further though...
HTH

**Comment by jmeas** [comment]
Fixed in https://github.com/babel/generator-babel-boilerplate/pull/289

Will release later today!
