### ISSUE TITLE
[DEPRECATION NOTICE] Esperanto is no longer under active development. 

### ISSUE THREAD

**Issue by mcbain** [babel/generator-babel-boilerplate#288]
```
To convert an ES6 module to another format, consider using Babel (https://babeljs.io)
```

**Comment by jmeas** [comment]
Thanks for the issue, @mcbain ! This seems similar to #219, so I'm going to close it as a duplicate.

Thanks again!

**Comment by mcbain** [comment]
Ok, the last npm release is from august .. maybe worth an update
