### ISSUE TITLE
Consider using Yeoman API over `npm whoami`

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#301]
[Ref](http://yeoman.io/generator/actions_user.html)

@megawac any thoughts on this? Iirc you implemented the original `npm whoami` code, or was that @thejameskyle?

**Comment by jmeas** [comment]
Thinking more about it, it makes more sense to use the `npm` user for the package.json author, and then the GitHub user for the repository URL. Folks whose npm user isn't the same as GitHub will have some trouble with what this package outputs.

**Comment by megawac** [comment]
Yeah the `whoami` stuff was an artificat of my original fork. Previously it was using `git.username()` which bugged me. I originally considered implementing such that if `whoami` fails it will resolve to

 - npm user name
 - git user name
 - OS user name

but that seemed more effort than it was worth at the time
