### ISSUE TITLE
Add link to the cost of transpiling

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#315]
@samccone did [some great research](https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016) that shows that the config in this library is pretty good for small libs. This should go in the README.

//cc @paulfalgout 

(this boilerplate may still switch to Rollup in the future for reasons other than strictly output size, but either way it's good news for the current setup)

**Comment by paulfalgout** [comment]
@Rich-Harris chimed in:  https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016/pull/17  Looks like Rollup might get significantly smaller

**Comment by samccone** [comment]
turns out mangling breaks everything (as I saw with closure... I am working on updating the source code to allow for this kind of mangling right now)

**Comment by paulfalgout** [comment]
how did webpack get away with it?  It's using the same library under the hood..  is webpack's mangle avoiding certain keywords by default?

**Comment by samccone** [comment]
it is using a slightly newer version of uglify that does not mangle prop names by default

**Comment by samccone** [comment]
WELCOME TO THE FUTURE OF HELL

**Comment by paulfalgout** [comment]
:fire: :mahjong: :fire:
