### ISSUE TITLE
The gulp mocha task ignores the `reporter` option

### ISSUE THREAD

**Issue by jcolemorrison** [babel/generator-babel-boilerplate#316]
Regardless of what you put in there (spec, dot, nyan, etc), it still shows un-colored, comparatively difficult, mocha output.

no this isn't a big deal - I just don't know where to look to fix it?  Anyone have an idea?

**Comment by jcolemorrison** [comment]
Okay nvm, apparently the first time I scaffolded it and installed the generator it happened.  But after scaffolding my second one it did not do this.

**Comment by jmeas** [comment]
Okay, awesome! Glad you were able to figure it out. Let me know if you have any other questions :)
