### ISSUE TITLE
Add a .jshintrc file

### ISSUE THREAD

**Issue by kristianmandrup** [babel/generator-babel-boilerplate#322]
Tried to oen a scaffolded project in Atom. Got loads of "errors".
To fix it, I had to add a `.jshintrc` file

```json
{
    "node": true,
    "esnext": true,
    "bitwise": true,
    "camelcase": false,
    "curly": true,
    "eqeqeq": true,
    "immed": true,
    "indent": 2,
    "latedef": "nofunc",
    "newcap": false,
    "noarg": true,
    "quotmark": "single",
    "regexp": true,
    "undef": true,
    "unused": false,
    "strict": false,
    "trailing": true,
    "smarttabs": true,
    "white": false,
    "globals": {
        "it": true,
        "describe": true,
        "before": true,
        "beforeEach": true,
        "after": true,
        "afterEach": true,
        "exports": true
    }
}
```

**Comment by jmeas** [comment]
Hmmm...that's unexpected! This project doesn't use JSHint out-of-the-box (though it's easy to swap it in manually). Do you have a JSHint plugin for Atom that lints all of your JS?

**Comment by kristianmandrup** [comment]
yeah, I think that is the problem. I had to make the plugin to ignore certain globals such as `describe`, `it` etc.

**Comment by megawac** [comment]
Which jshint plugin are you using? I thought `linter-jshint` (http://atomlinter.github.io/) only applies itself if it sees a `.jshintrc` file, similar for `linter-eslint`

**Comment by kristianmandrup** [comment]
https://github.com/sindresorhus/atom-jshint

**Comment by jmeas** [comment]
Glad it got worked out, @kristianmandrup ! :v:
