### ISSUE TITLE
Remove now-deprecated JSCS

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#327]
[Ref](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.8hl6oipg6)

**Comment by paulfalgout** [comment]
😭

**Comment by hzoo** [comment]
Still going to be supported but yeah we want people to switch 👍

**Comment by hzoo** [comment]
Still going to be supported for a while but yeah we want people to switch 👍
