### ISSUE TITLE
Yeoman isn't happy 😿 

### ISSUE THREAD

**Issue by paulfalgout** [babel/generator-babel-boilerplate#329]
https://travis-ci.org/babel/generator-babel-boilerplate/builds/127619132

**Comment by jmeas** [comment]
yikes 😛

**Comment by jmeas** [comment]
Will you have any time to look into this, @paulfalgout ?

**Comment by jmeas** [comment]
I'm shooting to tackle this (and a couple of other issues) this week.

**Comment by paulfalgout** [comment]
:+1: i am going to have more time for OSS in the near future.

**Comment by jmeas** [comment]
No problem. I figure you're busy planning to move / moving / doing other more important things :v:
