### ISSUE TITLE
Remove babel-eslint from generated lib?

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#349]
ESLint supports the most basic stuff based on the README here:

https://github.com/babel/babel-eslint

@paulfalgout / @megawac thoughts?

**Comment by paulfalgout** [comment]
Oh nice.. That readme note was added less than 2 weeks ago.  Yeah. I don't see a need for it.  If you're getting into the advanced babel stuff, you shouldn't have trouble adding babel-eslint..  And in the past this lib has been a headache as apparently it's a bit hacky.

**Comment by jmeas** [comment]
Resolved by #353
