### ISSUE TITLE
Shouldn't bower.json include sourcemap?

### ISSUE THREAD

**Issue by marcandre** [babel/generator-babel-boilerplate#358]
Shouldn't the bower.json include both `dist/lib.js` and `dist/lib.js.map`?

One user of `parsley` has issues because one of his grunt tasks notices the link to the `.map` in the main js file and then complains it can't be found (as it wasn't copied over)

**Comment by jmeas** [comment]
This boilerplate doesn't include bower.json , since not everyone uses it, yet it takes 2 secs to set up. Gonna close since the issue is unrelated to this project, but I'll take a look at the Parsley issue and try to help ✌️

**Comment by marcandre** [comment]
Oh, sorry, I thought `bower.json` was generated, I should have checked 😊

**Comment by jmeas** [comment]
No problem at all!
