### ISSUE TITLE
Stop shipping source map for transpiled files

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#359]
This library ships two maps: one for transpiled files, and one for minified files. The transpiled map only makes sense if:

1. the libs are distributed with the source files
2. the consumer sets up their browser to serve the source files

The first of those points is generally true for users of the babel boilerplate since we don't exclude the src directory from package.json by default (maybe we should?). But the 2nd requirement is pretty steep, and probably isn't true for most consumers.

For this reason, I think we should stop shipping the transpiled map and only ship the minified one.

//cc @megawac @paulfalgout

**Comment by megawac** [comment]
You aren't required to have the source files available in order to view
source map files. However I'm = to this proposal

**Comment by jmeas** [comment]
I'll have to double-check to verify, but my understanding is that you do, since it has the names of the files and the path to access them within the map.

> However I'm = to this proposal

Does that mean you don't have a strong feeling either way? :P

**Comment by megawac** [comment]
> I'll have to double-check to verify, but my understanding is that you do, since it has the names of the files and the path to access them within the map.

Nope, the entire source contents are stored and references in source maps (thats why map files are so damn big)

> Does that mean you don't have a strong feeling either way? :P

Yep

**Comment by jmeas** [comment]
> Nope, the entire source contents are stored and references in source maps (thats why map files are so damn big)

Interesting. If this is the case, then I won't make this change.

**Comment by jmeas** [comment]
The [gulp-sourcemap docs](https://github.com/floridoo/gulp-sourcemaps) confirm that the content ships w. the map :v:

**Comment by PolGuixe** [comment]
I am getting this error in Chrome console with a package I made with this boilerplate: `Failed to parse SourceMap`. 

But the map is under the `/dist` folder.

**Comment by PolGuixe** [comment]
I just opened a new issue here: https://github.com/babel/generator-babel-boilerplate/issues/382
