### ISSUE TITLE
Exclude /src directory from npm package by default?

### ISSUE THREAD

**Issue by jmeas** [babel/generator-babel-boilerplate#360]
Should the src directory be excluded from the npm package?

Pros:

- quicker downloads for consumers

Cons

- consumers can't go into node_modules to see the source. Is that a problem? Not sure.

//cc @megawac @paulfalgout

**Comment by megawac** [comment]
The main disadvantage is for people trying to build the src/ files themselves using tooling such as webpack or rollup. I'd say no, don't ignore by default

**Comment by jmeas** [comment]
K, cool. Easy enough to add in manually (1 line change!) if folks want.
