### ISSUE TITLE
npm test from clean project yields eslint error

### ISSUE THREAD

**Issue by ixtli** [babel/generator-babel-boilerplate#363]
did `yo babel-boilerplate`, answered questions, then did `npm test`. That, and all other npm run commands result in an error about eslint not knowing where to look for `.globals.json`:

```
Error: Cannot read config file: /Users/ixtli/Downloads/foo/node_modules/setup/.globals.json
Error: ENOENT: no such file or directory, open '/Users/ixtli/Downloads/foo/node_modules/setup/.globals.json'
Referenced from: /Users/ixtli/Downloads/foo/test/.eslintrc
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at readFile (/Users/ixtli/Downloads/foo/node_modules/eslint/lib/config/config-file.js:71:15)
    at loadJSONConfigFile (/Users/ixtli/Downloads/foo/node_modules/eslint/lib/config/config-file.js:121:41)
    at loadConfigFile (/Users/ixtli/Downloads/foo/node_modules/eslint/lib/config/config-file.js:213:26)
    at load (/Users/ixtli/Downloads/foo/node_modules/eslint/lib/config/config-file.js:500:18)
    at /Users/ixtli/Downloads/foo/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/Users/ixtli/Downloads/foo/node_modules/eslint/lib/config/config-file.js:363:28)
```

That file exists where it should (./test/setup/) but it seems like `.eslintrc` is using a relative path which is being resolved to node_modules for some reason.

Tried on both node 6.2.2 and 4.2.2.

**Comment by ixtli** [comment]
oh also, i did not have eslint installed globally when i ran these commands. i installed it globally, reinstalled node modules, and retried the commands and i get the same error.

**Comment by jmeas** [comment]
Thanks! I'll take a look today.

**Comment by jmeas** [comment]
This is the oddest thing – I can't reproduce it. @paulfalgout / @megawac would either of you have a sec to try this?

**Comment by ixtli** [comment]
:( For what it's worth I was able to make this happen on a separate machine
which had 4.2.2 installed.

**Comment by jmeas** [comment]
Ah, look at that. It must be an upstream bug: https://github.com/eslint/eslint/issues/6489

**Comment by ixtli** [comment]
oh well done. thanks for doing the googlin' :)

**Comment by jmeas** [comment]
> oh well done. thanks for doing the googlin' :)

No problem! If you restrict your version of ESLint, you should be able to avoid it. Have you been able to get past the problem?

**Comment by jmeas** [comment]
@ixtli does the latest eslint cause an error for you?

**Comment by jmeas** [comment]
After some more investigating, I don't think that the above issue is the problem.

I've tried on two different macs and can't reproduce this, so I'm going to close for now. @ixtli if you want to pair or spend more time trying to figure this out, then let me know.

If anyone else runs into this issue, **please comment here** and we can keep the discussion going!

**Comment by ixtli** [comment]
Oh I'm sorry I missed the Jul 15th message :( If I have reason to come back to this I will reopen. Thanks for your help :D

**Comment by jmeas** [comment]
> Oh I'm sorry I missed the Jul 15th message :(

No problem!

> If I have reason to come back to this I will reopen. Thanks for your help :D

Sounds good :)
