### ISSUE TITLE
Move from plumber to pump?

### ISSUE THREAD

**Issue by paulfalgout** [babel/generator-babel-boilerplate#388]
I haven't really looked into this much, but at first glance it seems nice and I _think_ they roughly solve the same problem...  I could be _way_ off here.

https://github.com/terinjokes/gulp-uglify/tree/master/docs/why-use-pump

**Comment by jmeas** [comment]
Looks like they solve the same problem. I'm 100% open to switching if it has some benefits over plumber 👍 

Would you have time to do more research to make a short pros/cons list?

**Comment by jmeas** [comment]
@paulfalgout, I think for now we should stick with plumber. There are two reasons:

1. The first is aesthetic. I prefer plumber's API a little more than pump's, as I dislike wrapping the whole pipe functionality.
2. If there was a big win in functionality, then maybe I could get over reason 1 and switch to pump. But it actually looks like we'd be losing some functionality. One of the reasons I like plumber is that it swallows errors altogether, preventing the stream from exploding. This is useful for our long-running task for building the app for the unit tests as changes are made. It doesn't seem like errors can be swallowed altogether with pump? In other words, it seems like the stream must always exit when there is an error?

Gonna close this issue for now, but I'm happy to reopen and keep the conversation going if you / anyone else feels that pump is the right way to go!
